apiVersion: v1
kind: Service
metadata:
  name: turing-machine-ide
  namespace: uhmarcel
  labels:
    name: turing-machine-ide

spec:
  type: NodePort
  selector:
    app: turing-machine-ide
  ports:
    - name: entry
      port: 80
      targetPort: 80
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: turing-machine-ide
  namespace: uhmarcel
  labels:
    name: turing-machine-ide
spec:
  selector:
    matchLabels:
      app: turing-machine-ide
  replicas: 2
  template:
    metadata:
      labels:
        app: turing-machine-ide
    spec:
      containers:
        - name: turing-machine-ide
          image: uhmarcel/turing-machine-ide:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
